### PR TITLE
Fix ensure-index issue with rx-mongo 0.13.0 (issue #184)

### PR DESCRIPTION
**Pull request by ymeymann**
I am trying to address https://github.com/scullxbones/akka-persistence-mongo/issues/184, please take a look. Tested it locally with rx-mongo 0.13 and it works well in my project.

### CODE REVIEW

**Comment by scullxbones** [comment]
If you can pull the version change out of `build.sbt` i'll handle that on release.  Otherwise, looks like it should work!

**Comment by ymeymann** [comment]
Just did, thanks a lot!

**Comment by scullxbones** [comment]
I'll need to figure out why the tests continue to fail before merging this.  Are the tests passing for you locally?

**Comment by scullxbones** [comment]
Closed by #208 - thanks for helping to get this done!

**Pull request closed without merging**
