### PR TITLE
Makes buffer size can be setting up from properties

### PR DESCRIPTION
**Pull request by Fabszn**
This PR aims to propose a way to setting up the buffer size of stream.

Currently i am faced with an issue, because I loose some messages (by droptail) in pre-production

### CODE REVIEW

**Comment by Fabszn** [comment]
Many thanks for your merged. 
Do you know when a new release could be done ?

**Comment by scullxbones** [comment]
I was thinking of putting it together with #190, but that one is a bit stalled out now.  Will give it another day and if it doesn't get moving, will get this one released by itself.

**Comment by Fabszn** [comment]
Thanks for your answer. It is perfect! Many thanks

**Comment by scullxbones** [comment]
Released with `v2.0.10` - thanks for the contribution!

**Comment by Fabszn** [comment]
Many many thanks !

**Pull request merged**
