### PR TITLE
support for reactivemongo 0.11

### LINKED ISSUE #29: Build for ReactiveMongo 0.11
With the new ReactiveMongo 0.11.0-M2 I'm getting the following errors:

```
java.lang.NoSuchMethodError: reactivemongo.api.MongoDriver$.apply(Lakka/actor/ActorSystem;)Lreactivemongo/api/MongoDriver;
	at akka.contrib.persistence.mongodb.RxMongoPersistenceDriver$class.driver(RxMongoPersistenceExtension.scala:50)
```

It has stable API now, so we should update driver for it.

### PR DESCRIPTION
**Pull request by alari**
fixes #29

### CODE REVIEW

**Comment by scullxbones** [comment]
Yes I started on updating to this version on the weekend. Between your changes and mine, it should work. I'm still trying to get all of the tests to pass. Thanks will take a look at this later today.

**Comment by scullxbones** [comment]
It looks like your tests are failing the exact same way as mine.  Will need to solve that before it can be released.

**Comment by alari** [comment]
Yep, I'm working on the tests. It takes forever on my desktop to launch it :(

**Comment by scullxbones** [comment]
@alari thanks for giving this a shot!

I worked through the issues and was able to release version 0.4.0 which upgrades to rx 0.11.

**Pull request closed without merging**
