### PR TITLE
#148: update to akka 2.5.1

### PR DESCRIPTION
**Pull request by thjaeckle**
Pull request for #148 
- updated to Akka 2.5.1
- used akka-persistence-query (dropped the -experimental)
- adjusted naming of "AllPersistenceIds" to "PersistenceIds" (renamed in final akka-persistence-query)

I'm not so used in making pull requests, if I can improve something, please let me know :)

### CODE REVIEW

**Comment by thjaeckle** [comment]
Oh, I just saw that RxMongoDriver seems to have  a problem with Akka 2.5
I just verified it for Cashbah driver.

**Comment by scullxbones** [comment]
Ah ok.  Will need to wait on RxMongo support then before resolving this one.  Hopefully they're close.

**Comment by thjaeckle** [comment]
ReactiveMongo 0.12.3 is compatible with Akka 2.5.1 - I will adjust in PR this evening.
If you want to change before, go ahead :)

**Comment by thjaeckle** [comment]
Should build now but the travis build only successfully built half of the diffent configurations with success?!

**Comment by scullxbones** [comment]
I was able to get it to build via re-running failed jobs.  I'd like to sequence #150 before this one for those that are still on `2.4.x` series and not ready to upgrade yet.

**Comment by thjaeckle** [comment]
Great.
Sure, I would do it the same way.

**Comment by thjaeckle** [comment]
Are there updates on the other issue?
If this would be delayed a lot there is still the option to merge the other issue to both, an akka 2.4 branch and an akka 2.5 one and release it for both major akka-persistence-mongo versions.

**Comment by scullxbones** [comment]
@thjaeckle - that could work, yes.  If #150 doesn't get resolved by Sunday evening - i'll go with that approach.  I think @filosganga has a 2.4.x solution for his team anyways - so probably not a hardship  for the current users of the functionality.

**Pull request merged**
