### PR TITLE
add an index on realtime collection on field "pid"

### PR DESCRIPTION
**Pull request by gbrd**
fixes issue #209

### CODE REVIEW

**Comment by gbrd** [comment]
Tailable cursors do not use indexes => my solution may not work.
https://docs.mongodb.com/manual/core/tailable-cursors/
still investigating..

**Comment by scullxbones** [comment]
Yep, I think i've skipped adding an index in the past due to that tailable cursor behavior.  Is this fix to address an issue you're seeing?  Maybe there's a different way to accomplish a fix?

**Comment by gbrd** [comment]
We use intensively live-queries, and it implies collection scan on mongodb each time.
The issue is that tailable cursor have bad performances and thus current implementation of live queries too.
I think it is usable only for low count of queries needs (1 per pid to implement writing in a query database for instance).

For my current needs, I will try to find another solution, without live queries. 
Later, maybe we could investigate an implementation of live queries in this plugin based of change stream https://docs.mongodb.com/manual/changeStreams/ )

**Comment by scullxbones** [comment]
Given that the collection is capped, it shouldn't be too terrible to run a collection scan.   That's why I think tailable cursors can come with this restriction.  Their sweet spot is low latency live updates, and to be long-lived for the most part.

> I think it is usable only for low count of queries needs (1 per pid to implement writing in a query database for instance).

If the use case involves creating lots of live queries and then discarding them, yep I'll bet that's a bad fit.  If that's your usage pattern, have you considered using the "allEvents" queries and sharing that stream?  Leaving the cursor open would help with the overhead of frequently opening and closing cursors.

> Later, maybe we could investigate an implementation of live queries in this plugin based of change stream 

It would be great to go to change streams, as that would mean no need to write each event twice (once in journal, once in capped realtime).  Unfortunately there either needs to be detection logic and branching to use those based on db server version, or need to wait until < 3.6 is unsupported.

**Pull request closed without merging**
