### PR TITLE
Wip akka24

### PR DESCRIPTION
**Pull request by twillouer**
:)

### CODE REVIEW

**Comment by scullxbones** [comment]
Thanks!  I already have moved 2.4.x to master, but let me merge it in.  That's a bad typo on the snapshot name :)

Is everything else working OK?  I think i'll probably cut a release today, and send a PR for the akka community plugins page.

**Comment by twillouer** [comment]
I'm not totally sure for the ClusterSharding. I'm trying to reproduce the problem, in the 
`akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer#fromBinary` method, the "manifest" parameter who is mandatory is like "BG", "AB", etc and with akka-persistence-mongo I got a "akka.cluster.sharding.ShardCoordinator$Internal$ShardRegionRegistered" (who is not handled by the serializer).

I suspect a problem when sending the manifest, but.. my 2 kids are not agree with time spending on my computer. I try later, but if you have an idea, you will be more fast than me :)

**Comment by scullxbones** [comment]
Ok sure. Let me add some tests around manifests. Thanks for the extra info!

**Comment by twillouer** [comment]
```
"Cluster-akka-contrib-persistence-dispatcher-25@3924" prio=5 tid=0x26 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer.fromBinary(ClusterShardingMessageSerializer.scala:148)
	  at akka.serialization.SerializerWithStringManifest.fromBinary(Serializer.scala:131)
	  at akka.serialization.Serialization$$anonfun$deserialize$3.apply(Serialization.scala:142)
	  at scala.util.Try$.apply(Try.scala:192)
	  at akka.serialization.Serialization.deserialize(Serialization.scala:142)
	  at akka.contrib.persistence.mongodb.Serialized.<init>(MongoDataModel.scala:29)
	  at akka.contrib.persistence.mongodb.Serialized$.apply(MongoDataModel.scala:38)
	  at akka.contrib.persistence.mongodb.Payload$.apply(MongoDataModel.scala:94)
	  at akka.contrib.persistence.mongodb.Event$.apply(MongoDataModel.scala:135)
	  at akka.contrib.persistence.mongodb.Atom$$anonfun$apply$3.apply(MongoDataModel.scala:153)
	  at akka.contrib.persistence.mongodb.Atom$$anonfun$apply$3.apply(MongoDataModel.scala:153)
	  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	  at scala.collection.immutable.List.foreach(List.scala:381)
	  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	  at scala.collection.immutable.List.map(List.scala:285)
	  at akka.contrib.persistence.mongodb.Atom$.apply(MongoDataModel.scala:153)
	  at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$batchAppend$1$$anonfun$1$$anonfun$apply$4.apply(CasbahPersistenceJournaller.scala:34)
	  at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$batchAppend$1$$anonfun$1$$anonfun$apply$4.apply(CasbahPersistenceJournaller.scala:34)
	  at scala.util.Try$.apply(Try.scala:192)
	  at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$batchAppend$1$$anonfun$1.apply(CasbahPersistenceJournaller.scala:34)
	  at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$batchAppend$1$$anonfun$1.apply(CasbahPersistenceJournaller.scala:34)
	  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	  at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	  at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	  at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$batchAppend$1.apply(CasbahPersistenceJournaller.scala:34)
	  at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$batchAppend$1.apply(CasbahPersistenceJournaller.scala:33)
	  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	  at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)
```

**Comment by scullxbones** [comment]
I'll research this, but one question I had was is this a journal that you've upgraded from a previous version?  I wonder if there's maybe a backward incompatibility problem with cluster sharding.  If the journal has only ever been used with 2.4 then that's probably not the problem

**Comment by twillouer** [comment]
No, my database is clean before each test

**Comment by twillouer** [comment]
`akka.contrib.persistence.mongodb.Serialized`

```
case class Serialized[C](bytes: Array[Byte], clazz: Class[C])(implicit ser: Serialization) extends Payload {
  type Content = C

  val hint = "ser"
  lazy val content = ser.deserialize(bytes, clazz) match {
    case Success(deser) => deser
    case Failure(x) => throw x
  }
}
```

The important part is "lazy", and all is now fine.

```
1f75dd78b6ca(mongod-3.0.4) store> db.akka_persistence_journal.find();
{
  "_id": ObjectId("55da30573d3c3f42818da7c7"),
  "pid": "/sharding/userAlertActorCoordinator",
  "from": NumberLong("1"),
  "to": NumberLong("1"),
  "events": [
    {
      "v": 1,
      "pid": "/sharding/userAlertActorCoordinator",
      "sn": NumberLong("1"),
      "_t": "ser",
      "p": BinData(0, "ClFha2thLnRjcDovL0V2c0NsdXN0ZXJAMTkyLjE2OC4wLjQxOjI1NTEvc3lzdGVtL3NoYXJkaW5nL3VzZXJBbGVydEFjdG9yIzE5NTg5NTg5NTc="),
      "_h": "akka.cluster.sharding.ShardCoordinator$Internal$ShardRegionRegistered",
      "_w": "4d4c16c1-5499-4202-a717-19e8531cacd0"
    }
  ],
  "v": 1
}
```

**Comment by twillouer** [comment]
Btw, my "correction" is not the more elegant, but perhaps she will boost performances :D

**Comment by twillouer** [comment]
(in this PR, there is not the lazy !)

**Comment by twillouer** [comment]
Because I was not able to write you a good unit test :-/

**Comment by scullxbones** [comment]
:) no worries.  i'm in the middle of trying to make sure i can reproduce the case.  the lazy doesn't make any sense to me as far as fixing an issue.  i'm happy to put it into the codebase - but i'd love to understand why it works...

**Comment by twillouer** [comment]
ok :)

I think, but I'm not sure, than the Serialized class try to unserialized the payload, but with the wrong manifest. So, the lazy is only resolving this problem (we don't need `content` when serializing, so lazy can be, perhaps, a good things to put in this code.
Perhaps a good workaround will be:
 - put the real manifest of the `PersistentRepr`
 - let the 'lazy' (because we don't need to deserialize the byte[] when we save an event)

**Comment by scullxbones** [comment]
Yep that totally makes sense to me.  I'm digging into the new `Serializer with String Manifest` code to see if I can figure out why it wouldn't have the correct manifest.  I don't think it's the same as the manifest on the `PersistentRepr`, but maybe it is.  The good news is I can duplicate it directly in a test case.

I do agree `content` can be lazy, since we don't need it until deserialization time.

**Comment by scullxbones** [comment]
Ok yeah there's some twists now with the `SerializerWithStringManifest` class.  I'm tracking this in #41

**Comment by scullxbones** [comment]
Hi @twillouer 

I ended up pushing another snapshot with the fix.  I was able to add a duplicating test case to make sure it will work with ClusterSharding, but it would be great if you had a chance to give this one a test drive.

Thanks!

**Comment by twillouer** [comment]
It works !
Thanks for your fix (and akka-persistence-mongo :))

**Pull request merged**
