### PR TITLE
Implemented allPersistenceIds and allEvents queries

### PR DESCRIPTION
**Pull request by matheuslima**
Implemented live queries of persistenceIds and allEvents. It made a small change in journal stream to make it more generic

### CODE REVIEW

**Comment by scullxbones** [comment]
This looks pretty good - I do like how quickly new queries can be created, it's a good framework you've built.  There's probably some that can be factored out, the stream shapes look pretty similar, but that can come later.  What are the downsides to using the `system.eventStream`?  One upside is that it's simpler, less code to maintain.  What are the other upsides?

**Comment by matheuslima** [comment]
I decided move to eventStream because is more generic and simpler. Another point is the previous implementation used a bounded concurrent hashmap to store all subscribers and I think this is bad.
The actual design is pretty simple, we have a capped collection and one cursor by node used to stream journaled events. This is good on point of view of performance.

**Comment by scullxbones** [comment]
Ok - the only negative I came up with is that we're publishing every event now into the event stream, vs before only events with active query-by-persistenceId were being published.

Cursor-by-node is close, and for most that will be the case.  It's a cursor per instance of the plugin.  Through configuration, you can get more than one instance of the plugin.  In this case, because we have N tailable cursors, we'd receive N events in the realtime half of the stream, where N is the number of instances of the plugin running.  I think the deduplicator would handle it, but it's one other thing to think about, since the event stream is a shared resource.

**Comment by matheuslima** [comment]
The behavior is exactly equals to before. The only one difference is that in previous implementation the events to subscribe was explicitly filtered. The previous used trait also used eventStream, however there was classification parameter to allow classify events by subscriber (or in the case, events by persistence id)

**Comment by scullxbones** [comment]
Thanks for the PR!

**Comment by bfil** [comment]
This implementation won't work in a clustered environment, would it? The actor system `eventStream` is local, so if a persistence query runs on three nodes, it will only receive realtime events from the publishers running on the same node.

**Quote from the akka docs** (http://doc.akka.io/docs/akka/snapshot/scala/event-bus.html):

> The event stream is a local facility, meaning that it will not distribute events to other nodes in a clustered environment (unless you subscribe a Remote Actor to the stream explicitly). If you need to broadcast events in an Akka cluster, without knowing your recipients explicitly (i.e. obtaining their ActorRefs), you may want to look into: Distributed Publish Subscribe in Cluster.

Or am I missing something?

**Comment by scullxbones** [comment]
It's a good question - we're using mongo for remote distribution of events via the capped `realtime` collection.  The event bus is an optimization to allow for a single open cursor to that collection per plugin instance.  Each event bus will broadcast events that show up on the `realtime` collection locally.

Let me know if this does/doesn't make sense.

**Comment by bfil** [comment]
Oh ok, so the `eventStream` is just an optimization, sounds good, thank you for the clarification.

**Pull request merged**
