### PR TITLE
simple pass-throu for rx' BSONDocuments

### PR DESCRIPTION
**Pull request by alari**
This PR doesn't introduce any new dependency, etc. It is completely transparent for client: client sends BSONDocument and receives the same thing. It's not coupled to bytecode representation of PersistentRepr, yet any binary serialization is.

This solution is not generic (it's implemented only for RX), but solves my problem.

scullxbones/akka-persistence-mongo#16

### CODE REVIEW

**Comment by scullxbones** [comment]
So this is interesting - you're basically saying, if the persisted payload is already a `BSONDocument`, then just stick that in mongo.  I hadn't thought about people using those for their events.

Here are the concerns that come to mind for me when merging this: 
* You're not persisting a bunch of fields though from the `PersistentRepr` - I assume these are the deprecated fields, since they're related to confirmations, but i'd like to continue to support those as one of the plugins that has been around for a while.  It's a tougher upgrade path for users with journal data.
* Something you've addressed in the Issue #16 thread, it's not generic.  Today a user can flip back and forth between the two drivers with very little effort.  
* I'd feel better about a `PartialFunction` approach where if it's not defined, we fall back to the binary encoding

**Comment by alari** [comment]
Well, I'm not going to use BSONDocuments as events, I want to handle (de)serialization on the client side, in my persistent actor.

I have implemented changes only on rx mongo due to simplicity of further serialization handling: I'm using play-json, and there's already a binding between json and bson in play's reactivemongo plugin.

So I'm using play json macro for json serialization and want to reuse those macros for storing events.

Well, I'll make the approach even simplier.

**Comment by scullxbones** [comment]
Ok, got it. From plugin perspective it looks the same.

**Comment by alari** [comment]
I've added all serializations, as well as simple casbah support for the similar scheme.

**Comment by scullxbones** [comment]
Cool. Will pull in your remote and play with it a bit locally.  Can you add a bit of sample code in the README.md file?  Just what a user would need to know to use this.  I assume it's as simple as creating an event containing either a bson document or a dbobject 

Thanks!

**Comment by alari** [comment]
There's also a couple of changes I'd like to make:

- Migrate to modern-looking build.sbt approach. It was quite difficult to make my IDEA work with the plugin.
- Implement the same BSON passing logic for snapshots.

What do you think?

**Comment by scullxbones** [comment]
Yep that sounds good to me for snapshots. Improved sbt sounds good, although I'll need to make sure it still works with my publishing plugin. 

I wouldn't worry yet about the json library integration. As long as users can easily use play json, lift json,  spray json, etc.

Will pull in your remote later this evening and play with it a bit locally.  Can you add a bit of sample code in the README.md file?  Just what a user would need to know to use this.  I assume it's as simple as creating an event containing either a bson document or a dbobject

**Comment by alari** [comment]
I have already added a couple of lines to readme.md

I'll take a look on sbt and snapshotter monday morning :)

**Comment by scullxbones** [comment]
Sounds great!  Thanks for helping out

**Comment by scullxbones** [comment]
Sorry, using my phone. Apparently have a double posting problem

**Comment by scullxbones** [comment]
Took a look at the code, it's looking good.  Clean approach, simple concept.  Couple things:

* I've been trying to use short field names (2 letter) to keep overhead small, can you shorten the new field names?
* Could you add some covering tests?  It doesn't have to be 100% covered, but happy path would be nice.  Would also help with some sample code for users.

Thanks again for the help!

**Comment by alari** [comment]
Can you update Scala version in Travis? I can't reproduce that bug from Travis locally.

**Comment by scullxbones** [comment]
It looks like play-iteratees version 2.3.5 doesn't exist in maven central.  Does another resolver need to be added?

**Comment by scullxbones** [comment]
Or are you saying with the latest changes we can no longer cross-build for 2.10 and 2.11?

**Comment by alari** [comment]
It's cross-built for 2.10.5 and 2.11.6. When I try to launch builder with legacy 2.11.0 (as Travis do), it says play-iteratees does not exist.

Locally (and in my jenkins with `sbt +test`) I have both 2.10 and 2.11 artifacts without a failure. And even going to use it in production.

Play-iteratees is a transitive dependency for rx-mongo. I have no idea why it could be unavailable in any case.

Can you try the build locally and update Scala versions in Travis to the latest releases?

**Comment by scullxbones** [comment]
Sure I will try tonight.  Have you tried updating `.travis.yml` in the root of the repository?  I see that `2.11.0` is specified there.  I would think that Travis would read this file, even on a pull request.

**Comment by scullxbones** [comment]
Cross-build looks good.  I think you just need to update the `.travis.yml` file in the root to use the versions of 2.10 and 2.11 that it should.  I would do it, but it wouldn't affect your PR as it's not in your branch/repo.

**Comment by scullxbones** [comment]
Or don't worry about it.  I can review the PR without that.  I'll add it if you don't.

**Comment by scullxbones** [comment]
So I think all this needs is those couple test cases, otherwise looks good.  I can fight with travis.

**Comment by scullxbones** [comment]
And the travis fix looks like adding the typesafe repository to the resolvers in `build.sbt`

**Comment by alari** [comment]
truly :) thanks :)

**Comment by sourcekick** [comment]
@alari What are you doing with your event to obtain the BSONDocument before you pass it to the journalling? Apply some simple function from http://reactivemongo.org/ ?

**Comment by alari** [comment]
@sourcekick I use play-json to format events, and then pass it to play's reactivemongo plugin, which allows json-bson conversion.

So I have created a trait to register event types and formats, providing persistJson and receiveRecoverJson helpers.

I can share that trait if you wish.

**Comment by scullxbones** [comment]
@alari are you able to write unit tests for this PR?  That's all I'm waiting on at this point.  If not, let me know and i'll write them.

**Comment by alari** [comment]
@scullxbones sorry I'm really overcommitted right now :( if you could help with tests, that's great!

**Comment by scullxbones** [comment]
Ok I understand.  If possible i'll get this merged and released this weekend.

**Comment by sourcekick** [comment]
@alari I am interested to see that trait, please share if possible.

**Comment by alari** [comment]
@sourcekick https://gist.github.com/alari/a792dfff066b9e7b787c

It's not ideal but it works.

Any comments or improvements are welcome :)

**Comment by alari** [comment]
The general idea is to serialize all events to documents, having a single key with the event name.

Play's json formats could be abstracted out.

**Comment by alari** [comment]
BWT there's BSON macro support for ReactiveMongo https://github.com/ReactiveMongo/ReactiveMongo/blob/0.10.5.x.akka23/macros/src/main/scala/macros.scala

it can be used to avoid play-json dependency and unnecessary json-bson marshalling.

**Pull request merged**
