### PR TITLE
workaround for DocumentDB to retrieve maxSequenceNr without sorting on the compound index

### PR DESCRIPTION
**Pull request by an-tex**
I guess nothing additionally to test here?

fixes https://github.com/scullxbones/akka-persistence-mongo/issues/328

### CODE REVIEW

**Comment by scullxbones** [comment]
Thanks - is that ordering of fields supported by DocumentDB?  I think the index declares them in the reverse order (PID, TO)

Also this fix needs to get applied to the reactivemongo driver.  Both need kept in-sync functionality wise.

**Comment by an-tex** [comment]
> Thanks - is that ordering of fields supported by DocumentDB? I think the index declares them in the reverse order (PID, TO)

oh boy, thanks! that needs to be in correct order (just checked). fixed
 
> Also this fix needs to get applied to the reactivemongo driver. Both need kept in-sync functionality wise.

ok pushed

**Comment by scullxbones** [comment]
Thanks for the contribution!

**Comment by an-tex** [comment]
Thanks for the quick responses!

**Pull request merged**
