### PR TITLE
[WIP] Add offset query

### PR DESCRIPTION
**Pull request by filosganga**
This PR aim to fix the #95 adding the timestamp field to the journal allowing to query events by offset.

The data need a migration to populate the field from the ObjectId.

### CODE REVIEW

**Comment by filosganga** [comment]
@scullxbones I have the migration on mongo shell script. What is the preferred way to deal with this changes? Doing a migration on the fly when the plugin is initialized? or offline? 

We have this already in production, and we have run the migration after the service was already running.

Ideally, you should run a couple of time before being able to use the query with the offset to make sure all the events have the timestamp field populated.

We are very keen to see this merged, we all the modification you would like to make.

I will need to revert the version, but in the meantime would be good if you can give me an initial feedback.

**Comment by scullxbones** [comment]
Thanks @filosganga - will take a look at it!

In the past have done an online migration process, and there is also the tools subproject that could be a good place to collect migrations.  Currently that's where the suffixed collection migration is run from.

**Comment by scullxbones** [comment]
I didn't much like the online forced data model upgrade process, but due to breaking backward compatibility it wasn't much of an option.  Given that this can run quietly in the background, and is backward compatible, that would be much better.  I think it would be good to provide a `.js` upgrade  to run in the mongo console for those that prefer to migrate that way.

Haven't had a chance to look deeply but scanning through the code looked good so far.  I'd prefer to not have to see code re-formatting edits next to code edits, when possible - but that was only in a few spots.

I hope to be able to dedicate some time to this tonight.

**Comment by filosganga** [comment]
Thanks @scullxbones I will provide the migration js in the tools project and also remove our specific version.

**Comment by scullxbones** [comment]
Seems like tests are failing even locally - are you seeing the same?

**Comment by filosganga** [comment]
@scullxbones I made a mistake in this PR. I will fix the tests as soon as I can.

**Comment by filosganga** [comment]
Closed as I have no more time working at that

**Pull request closed without merging**
